settings:
  title: 'Status Page'
  url: 'https://status.pingsut.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: SewaMobilJogja # unique identifier
    name: SewaMobilJogja
    description: 'Sewa Mobil Jogja' # default=empty
    url: 'https://sewamobiljogja.biz.id/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: BlogPingsutCom # unique identifier
    name: BlogPingsutCom
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://blog.pingsut.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  # - id: tantzswasty.my.id # unique identifier
  #   name: tantzswasty
  #   description: 'You write code. They handle the rest.' # default=empty
  #   url: '47.245.104.181' # URL to fetch
  #   method: GET # default=GET
  #   expectStatus: 200 # operational status, default=200
  #   followRedirect: false # should fetch follow redirects, default=false
  #   linkable: true # allows the title to be a link, default=true

  # - id: ali # unique identifier
  #   name: ali
  #   description: 'You write code. They handle the rest.' # default=empty
  #   url: '47.245.104.181' # URL to fetch
  #   method: CONNECT-IP # default=GET
  #   expectStatus: 200 # operational status, default=200
  #   followRedirect: false # should fetch follow redirects, default=false
  #   linkable: true # allows the title to be a link, default=true

  # - id: www-cloudflare-com
  #   name: www.cloudflare.com
  #   description: 'Built for anything connected to the Internet.'
  #   url: 'https://www.cloudflare.com'
  #   method: GET
  #   expectStatus: 200
  #   linkable: true # allows the title to be a link, default=true

  # - id: blog-cloudflare-com
  #   name: The Cloudflare Blog
  #   url: 'https://blog.cloudflare.com/'
  #   method: GET
  #   expectStatus: 200
